version: '3.8'

services:
  maap:
    container_name: maap
    build:
      context: .
      args:
        GIT_COMMIT: 12345
    command:
      - gunicorn maap.wsgi:application --bind 0.0.0.0:8000 --workers 3
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env.dev
    networks:
      - default
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      #- media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - maap
volumes:
  #app:
  static_volume:

networks:
    front:
        driver: macvlan
        driver_opts:
            parent: eth0.10
        ipam:
            config:
                - subnet: 192.168.31.0/24
                  gateway: 192.168.31.1

