# Generated by Django 3.0.5 on 2020-06-01 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaapReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_rep', models.FileField(blank=True, null=True, upload_to='mainapp.Report/bytes/filename/mimetype')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaapLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=64, verbose_name='s_time')),
                ('s_time', models.CharField(blank=True, max_length=64, verbose_name='s_time')),
                ('f_time', models.CharField(blank=True, max_length=64, verbose_name='f_time')),
                ('mode', models.CharField(blank=True, max_length=12, verbose_name='mode')),
                ('ans_amount', models.PositiveIntegerField(default=1, verbose_name='ans_amount')),
                ('ans_correct', models.PositiveIntegerField(default=0, verbose_name='ans_correct')),
                ('nx', models.PositiveIntegerField(default=12, verbose_name='nx')),
                ('ny', models.PositiveIntegerField(default=10, verbose_name='ny')),
                ('ax', models.PositiveIntegerField(default=50, verbose_name='ax')),
                ('sx', models.PositiveIntegerField(default=50, verbose_name='sx')),
                ('two_digit', models.PositiveIntegerField(default=1, verbose_name='two_digit')),
                ('no_minus', models.PositiveIntegerField(default=1, verbose_name='no_minus')),
                ('no_dec_mul', models.PositiveIntegerField(default=1, verbose_name='no_dec_mul')),
                ('hist_depth', models.PositiveIntegerField(default=5, verbose_name='hist_depth')),
                ('favor_thresold_time', models.PositiveIntegerField(default=15, verbose_name='hist_depth')),
                ('hist', models.CharField(blank=True, max_length=256, verbose_name='hist')),
                ('favor_ans', models.CharField(blank=True, max_length=256, verbose_name='hist')),
                ('qst_time', models.CharField(blank=True, max_length=12, verbose_name='mode')),
                ('mult', models.PositiveIntegerField(default=1, verbose_name='mult')),
                ('addi', models.PositiveIntegerField(default=1, verbose_name='addi')),
                ('subt', models.PositiveIntegerField(default=1, verbose_name='subt')),
                ('a1', models.PositiveIntegerField(default=0, verbose_name='a1')),
                ('b1', models.PositiveIntegerField(default=0, verbose_name='b1')),
                ('c1', models.PositiveIntegerField(default=0, verbose_name='c1')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MaapReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
