# Generated by Django 3.0.2 on 2020-03-04 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaapLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=24, verbose_name='s_time')),
                ('s_time', models.CharField(blank=True, max_length=12, verbose_name='s_time')),
                ('f_time', models.CharField(blank=True, max_length=12, verbose_name='f_time')),
                ('mode', models.CharField(blank=True, max_length=12, verbose_name='mode')),
                ('ans_amount', models.PositiveIntegerField(null=True, verbose_name='ans_amount')),
                ('ans_correct', models.PositiveIntegerField(null=True, verbose_name='ans_correct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
