# Generated by Django 3.0.5 on 2020-07-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maaplesson',
            name='avg_ans_time',
            field=models.PositiveIntegerField(default=0, verbose_name='avg_ans_time'),
        ),
        migrations.AddField(
            model_name='maaplesson',
            name='last_ans_time',
            field=models.PositiveIntegerField(default=0, verbose_name='last_ans_time'),
        ),
    ]
