# Generated by Django 3.0.5 on 2020-07-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200719_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maaplesson',
            old_name='last_ans_time',
            new_name='ans_sum',
        ),
    ]
