# Generated by Django 3.0.5 on 2020-08-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_maaplesson_divn'),
    ]

    operations = [
        migrations.AddField(
            model_name='maaplesson',
            name='wrong_ans',
            field=models.TextField(blank=True, verbose_name='wrong_ans'),
        ),
        migrations.AlterField(
            model_name='maaplesson',
            name='favor_ans',
            field=models.TextField(blank=True, verbose_name='favor_ans'),
        ),
    ]
