# Generated by Django 3.0.5 on 2020-08-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200802_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maaplesson',
            name='ax',
            field=models.PositiveIntegerField(default=100, verbose_name='ax'),
        ),
        migrations.AlterField(
            model_name='maaplesson',
            name='sx',
            field=models.PositiveIntegerField(default=100, verbose_name='sx'),
        ),
    ]
