# Generated by Django 3.0.5 on 2020-08-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200820_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maaplesson',
            name='ax',
        ),
        migrations.RemoveField(
            model_name='maaplesson',
            name='favor_thresold_time',
        ),
        migrations.RemoveField(
            model_name='maaplesson',
            name='hist_depth',
        ),
        migrations.RemoveField(
            model_name='maaplesson',
            name='no_dec_mul',
        ),
        migrations.RemoveField(
            model_name='maaplesson',
            name='no_minus',
        ),
        migrations.RemoveField(
            model_name='maaplesson',
            name='nx',
        ),
        migrations.RemoveField(
            model_name='maaplesson',
            name='ny',
        ),
        migrations.RemoveField(
            model_name='maaplesson',
            name='sx',
        ),
        migrations.RemoveField(
            model_name='maaplesson',
            name='two_digit',
        ),
    ]
