# Generated by Django 3.0.5 on 2020-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200828_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='maaplesson',
            name='addi_cnt',
            field=models.PositiveIntegerField(default=0, verbose_name='addi_cnt'),
        ),
        migrations.AddField(
            model_name='maaplesson',
            name='divn_cnt',
            field=models.PositiveIntegerField(default=0, verbose_name='divn_cnt'),
        ),
        migrations.AddField(
            model_name='maaplesson',
            name='mult_cnt',
            field=models.PositiveIntegerField(default=0, verbose_name='mult_cnt'),
        ),
        migrations.AddField(
            model_name='maaplesson',
            name='subt_cnt',
            field=models.PositiveIntegerField(default=0, verbose_name='subt_cnt'),
        ),
    ]
